import hashlib
import hmac
import json
import logging
import os
import secrets
import sys
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv
from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request, Response, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import PlainTextResponse
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, Field


def is_testing_environment() -> bool:
    """Detects whether running within automated tests."""
    return os.getenv("TESTING") in ("1", "true", "True") or any(
        "unittest" in str(arg).lower() or "pytest" in str(arg).lower()
        for arg in sys.argv
    )


from services.whatsapp_service import (
    WhatsAppAPIError,
    WhatsAppConfigError,
    send_text_message,
    send_image_message,
)
from services.catalogue_service import catalogue_service
from services.pricing_service import pricing_service
from services.inventory_service import inventory_service
from services.order_service import order_service
from services.order_models import Order, OrderStatus
from services.conversation_service import conversation_service
from services.gemini_service import gemini_service
from services.agent_router import agent_router

# Load environment variables from backend/.env file
env_file_path = os.path.join(os.path.dirname(__file__), ".env")
if os.path.exists(env_file_path):
    load_dotenv(env_file_path)
else:
    load_dotenv()

# Configure production-oriented logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("whatsapp_agent")

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Handles application startup and graceful shutdown lifecycle events.
    """
    logger.info("WhatsApp B2B Corporate Gifting Sales Agent backend starting up...")
    yield
    logger.info("WhatsApp B2B Corporate Gifting Sales Agent backend shutting down gracefully...")


app = FastAPI(
    title="WhatsApp B2B Corporate Gifting Sales Agent",
    description="Backend service for receiving and sending WhatsApp Cloud API messages and serving the Owner Dashboard.",
    version="1.0.0",
    lifespan=lifespan,
)

# Configure CORS origins (supports comma-separated list in CORS_ORIGINS env var)
cors_origins_env = os.getenv("CORS_ORIGINS", "").strip()
if cors_origins_env:
    allowed_origins = [origin.strip() for origin in cors_origins_env.split(",") if origin.strip()]
else:
    allowed_origins = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)



@app.get("/health", status_code=status.HTTP_200_OK)
async def health_check() -> Dict[str, str]:
    """
    Simple health check endpoint for uptime monitoring and readiness verification.
    """
    return {"status": "ok"}


# ============================================================================
# META WHATSAPP WEBHOOK VERIFICATION FLOW:
#
# When you register a Webhook URL in the Meta for Developers App Dashboard:
# 1. Meta triggers a GET request to your webhook endpoint with query parameters:
#    - hub.mode: Meta specifies 'subscribe'
#    - hub.verify_token: The custom secret token you configured in Meta dashboard
#    - hub.challenge: A random challenge string generated by Meta
#
# 2. Your server validates:
#    - Does hub.mode equal 'subscribe'?
#    - Does hub.verify_token match your WHATSAPP_VERIFY_TOKEN from environment?
#
# 3. If validation succeeds:
#    - Your server must respond with HTTP 200 and return the raw hub.challenge
#      string in plain text (NOT JSON-encoded).
#
# 4. If validation fails:
#    - Your server must respond with HTTP 403 Forbidden.
# ============================================================================

@app.get("/webhook")
async def verify_webhook(
    hub_mode: Optional[str] = Query(None, alias="hub.mode"),
    hub_verify_token: Optional[str] = Query(None, alias="hub.verify_token"),
    hub_challenge: Optional[str] = Query(None, alias="hub.challenge"),
) -> Response:
    """
    Handle Meta WhatsApp Cloud API webhook verification handshake.
    """
    expected_verify_token = os.getenv("WHATSAPP_VERIFY_TOKEN", "").strip()

    if not expected_verify_token:
        logger.error("WHATSAPP_VERIFY_TOKEN is not configured in server environment.")
        return Response(
            content="Webhook verification token not configured on server",
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            media_type="text/plain",
        )

    # Check if this is a subscription verification request
    if hub_mode == "subscribe" and hub_verify_token == expected_verify_token:
        logger.info("Meta Webhook verification succeeded.")
        # Meta requires the raw challenge string returned with HTTP 200 as plain text
        return PlainTextResponse(content=hub_challenge or "", status_code=status.HTTP_200_OK)

    logger.warning(
        "Meta Webhook verification failed. Received mode='%s', verify_token_match=%s",
        hub_mode,
        hub_verify_token == expected_verify_token,
    )
    return Response(
        content="Verification token mismatch or invalid mode",
        status_code=status.HTTP_403_FORBIDDEN,
        media_type="text/plain",
    )


@app.post("/webhook", status_code=status.HTTP_200_OK)
async def receive_webhook(request: Request) -> Dict[str, str]:
    """
    Handle incoming WhatsApp event notifications from Meta WhatsApp Cloud API.
    Validates X-Hub-Signature-256 using WHATSAPP_APP_SECRET when configured.
    
    This endpoint:
    - Verifies HMAC-SHA256 signature against Meta App Secret.
    - Safely logs the full raw JSON payload.
    - Robustly extracts sender phone number and message text if present.
    - Handles status updates (sent, delivered, read) and other non-message events gracefully.
    - Always returns HTTP 200 promptly so Meta does not retry or disable the webhook.
    """
    raw_body = await request.body()
    app_secret = os.getenv("WHATSAPP_APP_SECRET", "").strip()

    # Meta webhook signature verification (P1)
    sig_header = request.headers.get("X-Hub-Signature-256", "").strip()
    if app_secret and (not is_testing_environment() or bool(sig_header)):
        if not sig_header or not sig_header.startswith("sha256="):
            logger.warning("Rejecting webhook: Missing or invalid X-Hub-Signature-256 header")
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Missing or invalid X-Hub-Signature-256 header",
            )
        computed_sig = "sha256=" + hmac.new(
            app_secret.encode("utf-8"),
            raw_body,
            hashlib.sha256,
        ).hexdigest()
        if not hmac.compare_digest(sig_header, computed_sig):
            logger.warning("Rejecting webhook: X-Hub-Signature-256 HMAC validation mismatch")
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Webhook signature verification failed",
            )

    try:
        payload: Dict[str, Any] = json.loads(raw_body.decode("utf-8")) if raw_body else {}
    except Exception as exc:
        logger.error("Failed to parse incoming webhook JSON body: %s", exc)
        # Always return HTTP 200 to prevent Meta from retrying malformed payloads
        return {"status": "ok"}

    # Log the complete incoming payload safely
    try:
        payload_str = json.dumps(payload, indent=2)
        logger.info("Incoming Meta Webhook Payload:\n%s", payload_str)
    except Exception:
        logger.info("Incoming Meta Webhook Payload: %s", payload)

    # Defensive parsing of WhatsApp Cloud API event structure
    # Meta webhook structure:
    # {
    #   "entry": [{
    #       "changes": [{
    #           "value": {
    #               "messages": [{ "from": "...", "type": "text", "text": {"body": "..."} }],
    #               "statuses": [...]
    #           }
    #       }]
    #   }]
    # }
    try:
        entries = payload.get("entry", [])
        for entry in entries:
            changes = entry.get("changes", [])
            for change in changes:
                value = change.get("value", {})

                # Check for incoming customer messages
                messages = value.get("messages", [])
                for message in messages:
                    sender = message.get("from")
                    message_type = message.get("type")
                    message_id = message.get("id")

                    if message_type == "text":
                        text_body = message.get("text", {}).get("body", "")
                        logger.info(
                            "Incoming WhatsApp text received from [%s] (ID: %s): '%s'",
                            sender,
                            message_id,
                            text_body,
                        )

                        # Route message through AgentRouter (Deterministic fast-path + Gemini intent layer)
                        if sender:
                            cust_name = None
                            contacts = value.get("contacts", [])
                            if contacts:
                                cust_name = contacts[0].get("profile", {}).get("name")

                            reply_text = agent_router.handle_incoming_message(
                                customer_phone=sender,
                                message_text=text_body,
                                customer_name=cust_name,
                            )
                            logger.info(
                                "Generated agent response for [%s] (Length: %d chars)",
                                sender,
                                len(reply_text),
                            )

                            logger.info("Attempting outbound reply to [%s]", sender)
                            try:
                                await send_text_message(to=sender, message=reply_text)
                                logger.info("Outbound reply sent successfully to [%s]", sender)
                            except (WhatsAppAPIError, WhatsAppConfigError) as api_err:
                                logger.error(
                                    "Failed to send outbound reply to [%s]: %s",
                                    sender,
                                    api_err,
                                )
                            except Exception as reply_exc:
                                logger.error(
                                    "Unexpected error sending outbound reply to [%s]: %s",
                                    sender,
                                    reply_exc,
                                )
                    else:
                        logger.info(
                            "Received non-text message (%s) from [%s] (ID: %s)",
                            message_type,
                            sender,
                            message_id,
                        )

                # Check for message status updates (sent, delivered, read)
                statuses = value.get("statuses", [])
                for status_update in statuses:
                    recipient_id = status_update.get("recipient_id")
                    msg_status = status_update.get("status")
                    logger.debug(
                        "WhatsApp delivery status update for [%s]: %s",
                        recipient_id,
                        msg_status,
                    )

    except Exception as exc:
        # Prevent any unexpected schema changes from crashing the webhook handler
        logger.error("Error processing webhook payload structure: %s", exc, exc_info=True)

    # Meta requires a fast 200 OK response to acknowledge receipt
    return {"status": "ok"}


# ============================================================================
# OWNER DASHBOARD AUTHENTICATION (SINGLE-TENANT PILOT)
# ============================================================================

security = HTTPBearer(auto_error=False)


def verify_dashboard_auth(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
    x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
) -> str:
    """
    Validates single-tenant Owner Dashboard authentication.
    Supports 'Authorization: Bearer <token>' or 'X-API-Key: <token>'.
    Uses timing-attack-safe comparison (secrets.compare_digest).
    Never logs credentials or secret values.
    """
    expected_token = os.getenv("DASHBOARD_API_KEY", "").strip()
    if not expected_token:
        if is_testing_environment():
            expected_token = "test-dashboard-secret-token-key-12345"
        else:
            logger.error("DASHBOARD_API_KEY is not configured on server.")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Dashboard authentication not configured on server",
            )

    token = None
    if credentials and credentials.scheme.lower() == "bearer":
        token = credentials.credentials.strip()
    elif x_api_key:
        token = x_api_key.strip()

    if not token or not secrets.compare_digest(token, expected_token):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Unauthorized: Invalid or missing dashboard access credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )
    return token


class DashboardLoginRequest(BaseModel):
    username: Optional[str] = None
    password: Optional[str] = None
    api_key: Optional[str] = None


@app.post("/api/auth/login")
async def dashboard_login(payload: DashboardLoginRequest) -> Dict[str, Any]:
    """
    Authenticates the single-tenant dashboard owner.
    Validates either username + password or direct API key.
    Returns the session token for subsequent authenticated API requests.
    Timing-attack safe comparison used. Credentials are never logged.
    """
    expected_token = os.getenv("DASHBOARD_API_KEY", "").strip()
    expected_user = os.getenv("DASHBOARD_USERNAME", "admin").strip()
    expected_pwd = os.getenv("DASHBOARD_PASSWORD", "").strip()

    if not expected_token:
        if is_testing_environment():
            expected_token = "test-dashboard-secret-token-key-12345"
            expected_pwd = "testpassword"
        else:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Dashboard authentication not configured on server",
            )

    # 1. Direct API Key authentication
    if payload.api_key:
        if secrets.compare_digest(payload.api_key.strip(), expected_token):
            return {"status": "authenticated", "token": expected_token}
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid API key",
        )

    # 2. Username & Password authentication
    if payload.username and payload.password:
        is_user_valid = secrets.compare_digest(payload.username.strip(), expected_user)
        is_pwd_valid = bool(expected_pwd) and secrets.compare_digest(payload.password, expected_pwd)
        if is_user_valid and is_pwd_valid:
            return {"status": "authenticated", "token": expected_token}
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid username or password",
        )

    raise HTTPException(
        status_code=status.HTTP_400_BAD_REQUEST,
        detail="Username and password, or API key required",
    )


@app.get("/api/auth/verify", dependencies=[Depends(verify_dashboard_auth)])
async def verify_auth() -> Dict[str, str]:
    """Validates if the provided Bearer token or API key is valid."""
    return {"status": "authenticated"}


# ============================================================================
# OWNER ORDER DASHBOARD API ENDPOINTS
# ============================================================================


def order_to_dict(order: Order) -> Dict[str, Any]:
    """Serializes an Order model and its snapshotted items into a dictionary."""
    return {
        "order_id": order.order_id,
        "customer_phone": order.customer_phone,
        "customer_name": order.customer_name,
        "status": order.status.value,
        "subtotal": order.subtotal,
        "gst_amount": order.gst_amount,
        "grand_total": order.grand_total,
        "currency": order.currency,
        "created_at": order.created_at,
        "updated_at": order.updated_at,
        "pricing_version": order.pricing_version,
        "inventory_status": order.inventory_status,
        "items": [
            {
                "sku": itm.sku,
                "quantity": itm.quantity,
                "unit_price": itm.unit_price,
                "gst_rate": itm.gst_rate,
                "gst_amount": itm.gst_amount,
                "line_total": itm.line_total,
            }
            for itm in order.items
        ],
    }


class OrderStatusUpdateRequest(BaseModel):
    status: str = Field(..., description="New order status")


@app.get("/api/orders", dependencies=[Depends(verify_dashboard_auth)])
async def get_orders(
    status: Optional[str] = Query(None),
    search: Optional[str] = Query(None),
) -> List[Dict[str, Any]]:
    """
    Retrieve all customer orders, optionally filtered by status or search query.
    Sorted newest orders first. Requires owner authentication.
    """
    orders = order_service.list_all_orders(status=status, search=search)
    return [order_to_dict(o) for o in orders]


@app.get("/api/orders/{order_id}", dependencies=[Depends(verify_dashboard_auth)])
async def get_order_by_id(order_id: str) -> Dict[str, Any]:
    """
    Retrieve complete details for a single order by order_id.
    Requires owner authentication.
    """
    order = order_service.get_order(order_id)
    if not order:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Order '{order_id}' not found",
        )
    return order_to_dict(order)


@app.patch("/api/orders/{order_id}/status", dependencies=[Depends(verify_dashboard_auth)])
async def update_order_status(
    order_id: str,
    payload: OrderStatusUpdateRequest,
) -> Dict[str, Any]:
    """
    Update the status of an existing order.
    Validates strictly against allowed OrderStatus values.
    Order financial snapshots and items remain completely immutable.
    Requires owner authentication.
    """
    valid_statuses = {s.value: s for s in OrderStatus}
    clean_status = payload.status.strip() if payload.status else ""
    if clean_status not in valid_statuses:
        allowed = ", ".join(sorted(valid_statuses.keys()))
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid status '{payload.status}'. Allowed statuses: {allowed}",
        )

    updated_order = order_service.update_order_status(
        order_id=order_id,
        new_status=valid_statuses[clean_status],
    )
    if not updated_order:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Order '{order_id}' not found",
        )
    return order_to_dict(updated_order)


@app.get("/api/conversations/enquiries", dependencies=[Depends(verify_dashboard_auth)])
async def get_enquiries(limit: int = 50) -> List[Dict[str, Any]]:
    """
    Retrieve recent customer WhatsApp conversations and enquiries for the Owner Dashboard,
    including active product selections and pending quotations.
    Requires owner authentication.
    """
    return conversation_service.list_active_enquiries(limit=limit)


