-- =============================================================================
-- Migration: 004_message_audit_events.sql
-- Project: Mudhra B2B Corporate Gifting Platform
-- Description: Durable Supabase PostgreSQL store for WhatsApp lifecycle audit
--              events, webhook reliability metrics, and observability.
-- Multi-Tenant Ready: Includes tenant_id on all records (defaults to 'default').
-- =============================================================================

CREATE TABLE IF NOT EXISTS message_audit_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    correlation_id VARCHAR(128) NOT NULL,
    channel_message_id VARCHAR(128),
    customer_phone VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    direction VARCHAR(16) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    status VARCHAR(32),
    details JSONB DEFAULT '{}'::jsonb,
    is_test BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW())
);

CREATE INDEX IF NOT EXISTS idx_audit_tenant_created ON message_audit_events (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_is_test ON message_audit_events (tenant_id, is_test);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_correlation ON message_audit_events (tenant_id, correlation_id);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_wamid ON message_audit_events (tenant_id, channel_message_id);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_phone ON message_audit_events (tenant_id, customer_phone);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_direction ON message_audit_events (tenant_id, direction);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_event_type ON message_audit_events (tenant_id, event_type);

COMMENT ON TABLE message_audit_events IS 'Durable log of inbound/outbound WhatsApp lifecycle and delivery status events.';
COMMENT ON COLUMN message_audit_events.is_test IS 'Flag indicating whether the audit event was generated by automated testing or synthetic traffic.';

-- Enable Row Level Security (RLS)
ALTER TABLE message_audit_events ENABLE ROW LEVEL SECURITY;

-- Idempotent RLS Policy for service_role
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'message_audit_events' 
        AND policyname = 'Allow service role full access to message_audit_events'
    ) THEN
        CREATE POLICY "Allow service role full access to message_audit_events"
        ON message_audit_events
        FOR ALL
        TO service_role
        USING (true)
        WITH CHECK (true);
    END IF;
END
$$;
